version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tabdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: node-backend
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/tabdb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma generate &&
             npx prisma migrate dev --name init &&
             node src/index.js"

volumes:
  mysql_data:
